schema_version: 1

context:
  version: "0.1.2"

package:
  name: fps-yrooms
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/f/fps-yrooms/fps_yrooms-${{ version }}.tar.gz
    sha256: 2143166e1e1c1cfd07472ce0292e1407e2b43de1da171aa826bbf1f2ea922379

build:
  noarch: python
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build
  run:
    - python >=${{ python_min }}
    - jupyverse-api >=0.14.0,<0.15.0
    - jupyter_ydoc >=3.4.0,<4.0.0

tests:
  - python:
      imports: fps_yrooms
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: BSD-3-Clause
  license_file: COPYING.md
  homepage: https://github.com/jupyter-server/jupyverse/tree/main/plugins/yrooms
  summary: An FPS plugin for YRooms.

extra:
  recipe-maintainers:
    - davidbrochart
